name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # 'v'로 시작하는 태그가 푸시될 때 릴리즈를 생성

jobs:
  build:
    runs-on: macos-latest

    strategy:
        matrix:
            target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.2.1

      - name: Install Rust toolchain
        run: rustup target add ${{ matrix.target }}  # 대상 아키텍처 설치

      - name: Build the project
        run: cargo build --release --target ${{ matrix.target }}  # 각 아키텍처별로 릴리즈 빌드

      - name: Upload release binary
        uses: actions/upload-artifact@v4.4.3
        with:
          name: set_spotlight-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/set_spotlight  # 타겟별 바이너리 경로
        
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download arm64 release binary
        uses: actions/download-artifact@v4.1.8
        with:
          name: set_spotlight-aarch64-apple-darwin
      - name: Download x86_64 release binary
        uses: actions/download-artifact@v4.1.8
        with:
          name: set_spotlight-x86_64-apple-darwin

      - name: GH Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            set_spotlight-aarch64-apple-darwin
            set_spotlight-x86_64-apple-darwin
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{ github.ref }}
          draft: false
          prerelease: false
  