name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 'v'로 시작하는 태그가 푸시될 때 릴리즈를 생성

jobs:
  build:
    runs-on: macos-latest

    strategy:
        matrix:
            target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.2.1

      - name: Install Rust toolchain
        run: rustup target add ${{ matrix.target }}

      - name: Build the project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload release binary
        uses: actions/upload-artifact@v4.4.3
        with:
          name: set_spotlight-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/set_spotlight
        
  release:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download release binary
        uses: actions/download-artifact@v4.1.8
        with:
          name: set_spotlight-*
          merge-multiple: true
      - run: ls -R
      - name: GH Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            ${{ github.workspace }}/set_spotlight-aarch64-apple-darwin  
            ${{ github.workspace }}/set_spotlight-x86_64-apple-darwin
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            auto-generated release
          draft: false
          prerelease: false
  